version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myimagesdb
      MYSQL_USER: heb_user
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  myimages-app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"

volumes:
  mysql_data:
